### ISSUE TITLE
Configure for tmpfs to avoid writing to SD card (Read-Only File System)

### ISSUE THREAD

**Issue by Praneet9** [pez-globo/pufferfish-vent-software#107]
Configure File System to be read only to avoid writing system logs to SD Card.
Should support USB Mounting for backend File I/O.
We also need a script to do all the configuration.

**Comment by Praneet9** [comment]
@ethanjli 
I tested this with "overlayfs script" as well as with "Raspberry Pi Configuration" program
It breaks our current splash screen setup and the old default pi splash screen replaces the pufferfish one with both the tests.
Did you see this same behaviour?

**Comment by ethanjli** [comment]
(copied from Slack)

When I enable OverlayFS through the graphical raspberry configuration, I see the rainbow square, then a black screen, then a brief flash of the raspberry logo over a white screen with "Welcome to the Raspberry Pi Desktop", then the wallpaper; our custom boot screen is not visible. If I then disable OverlayFS, then the previous boot screen behavior (i.e. our boot screen shows up) returns.

If I run `sudo apt-get purge plymouth` and then enable OverlayFS and then restart, then the boot sequence looks normal again: no rainbow square, then 2 lines of console output about e2fsck doing a rootfs filesystem check, and then our boot screen shows; on shutdown there is more console output briefly visible on screen. So somehow enabling OverlayFS causes the default plymouth boot screen to return. I think it is fine to just purge plymouth if plymouth causes our usual boot screen to be very short.
