### ISSUE TITLE
Nginx Configuration

### ISSUE THREAD

**Issue by Sudhir-dev** [pez-globo/pufferfish-vent-software#174]
Need to update Nginx configuration to resolve 404 error on refresh of UI.

1. Update Configuration in Nginx located at "/etc/nginx/sites-available/default" 
2. Replace "location" block with following block

        location / {
                try_files $uri $uri/ /index.html;
        }

(Need to restart nginx once configuration has been changed)

**Comment by Sudhir-dev** [comment]
@Praneet9 As you are already making changes in nginx.conf, I believe we could also update "error_page 404 /;" along with that.

**Comment by Praneet9** [comment]
Yes, that should make configuring Nginx easier as we will only be dealing with one single file.
