### ISSUE TITLE
Idle flow at ventilator startup.

### ISSUE THREAD

**Issue by Tanmay06** [pez-globo/pufferfish-vent-software#223]
**Describe the bug**
When the ventilator is started we get around 2-3 l/min of idle flow until the frontend has been completely booted up. This starts when the RaspberryPi OS has booted up till the frontend is loaded. 

**To Reproduce**
1. Open the Air and O2 inputs.
2. Turn on the ventilator.

**Expected behavior**
There should not be any flow until instructed through the frontend.

**Comment by ethanjli** [comment]
My current hypothesis is that the PWM peripherals for driving the valves are not initialized before setup, and that initializing them to 0 may fix this problem. We'll need some testing to check this.
