### ISSUE TITLE
Implement ability to set multiple buffers in MockDevice

### ISSUE THREAD

**Issue by renjipanicker** [pez-globo/pufferfish-vent-software#254]
**Is your feature request related to a problem? Please describe.**
In its current implementation, the MockDevice has single pair of buffers, one for reads and one for writes. When testing scenarios where reads/writes are performed multiple times, this single buffer-pair is insufficient.

**Describe the solution you'd like**
Implement the ability to set a array of buffers for reading and writing, so that any higher-level object, including test cases, can read/write a sequence of buffers.

**Comment by ethanjli** [comment]
@renjipanicker Would it be possible for either you or @rohanpurohit to take up this issue? If so, I'll remove myself from the list of assignees and add one of you to it

**Comment by renjipanicker** [comment]
I'll take it up. I should have assigned it to myself earlier.
