### ISSUE TITLE
Vector::copy_from and calling code should detect when copy is truncated to prevent overflow

### ISSUE THREAD

**Issue by ethanjli** [pez-globo/pufferfish-vent-software#282]
`Util::Vector::copy_from` returns silently, even if it couldn't copy all source data as requested because its internal buffer filled up in the middle as a result of the copy. It should return an `IndexStatus` indicating whether an out-of-bounds error was averted - i.e. it should copy what it can, and use `IndexStatus::out_of_bounds` to indicate if it was requested to copy data which would've been out of bounds of its internal buffer. Anything which uses Vector::copy_from should also check and handle its return code. For example, `Protocols::CRCElement::parse` and `Datagram::parse` currently silently truncate data if their payload buffers are shorter than necessary to hold all data from the input buffer, because that is the behavior of `Util::Vector::copy_from`.

For CRC elements, it may also be possible to enforce this through the compiler: we could add a static assertion into `CRCElement::parse` and/or `CRCElementReceiver::transform` comparing `input_size` against `PayloadBuffer::max_size()`, and into `CRCElement::write` and/or `CRCElementSender::transform` comparing `output_size` against `PayloadBuffer::max_size()`. These static assertions make the CRC element classes less flexible in ways we don't care about, so it could be good to add this extra level of checking if the compiler allows it. The same applies to the datagram classes.

**Comment by ethanjli** [comment]
@rohanpurohit I think this was one of those issues I had lost when my tabs crashed!

**Comment by rohanpurohit** [comment]
oh ok! will work on it.
