### ISSUE TITLE
Split up deploy.sh into install/setup and locking up the system

### ISSUE THREAD

**Issue by rohanpurohit** [pez-globo/pufferfish-vent-software#314]
Currently, running the deploy.sh will do the following:
- install all the dependencies.
- setup all the required services.
- lockout the file system by generating hashes for all the files to avoid tampering.
- locks and removes sudo permissions from pi users.
- disables all network-related services.

If there is any error while installing/setting up the services, the dev is locked out of the pi and needs to reflash the raspberry pi sd card and re-do the process from the beginning.
therefore, we propose to split up the process of install/setup and locking the user out of the system into two different scripts, one as deploy/install/setup and the second one as lock.sh

**Comment by ethanjli** [comment]
The read-only filesystem config script should also be moved from deploy.sh into lock.sh.

For usability, maybe deploy.sh shouldn't call install.sh. Instead, we could make a deploy_full.sh which calls install.sh, deploy.sh, and lock.sh.
