### ISSUE TITLE
ValueClicker behaves really weirdly with the rotary encoder

### ISSUE THREAD

**Issue by ethanjli** [pez-globo/pufferfish-vent-software#356]
In the quickstart screen, when the rotary encoder is used to adjust a value, the value keeps changing by a nondeterministic amount (e.g. flow increases by 60, or it decreases by 50, or by 20). This bug was introduced with the new functionality for adjusting values from the Quick Start screen and the Alarm Limits screen and the Settings screen (maybe it's related to ValueClicker.tsx?)

**Comment by rohanpurohit** [comment]
This bug is present in `all pages` except the multistep popup alarm modal, which would include `AlarmsPage`, Settings Page Valueclickers in `Display` tab etc
