### ISSUE TITLE
Improve code comments and refactor/improve code in modules/app

### ISSUE THREAD

**Issue by rohanpurohit** [pez-globo/pufferfish-vent-software#390]
This issue is split off from [#359 comment](https://github.com/pez-globo/pufferfish-software/pull/359#issuecomment)

In general:

- Cross-checking all code comments with your replies to the questions we added as Github comments above, to make sure they include all of the clarifying information you provided for anything which you haven't already included in the code comments. This would also include any resolutions to the unresolved comments listed above.

modules/app:
- staticStart and having a different react component for the Start button in the landing page vs. the "Start/Stop Ventilation" button in the other pages, to simplify the code: #359 (comment)
- Removing isVentilatorOn, which is dead code: #359 (comment) , #359 (comment) . This may also remove the need for a landingLabel useState? That was discussed in #359 (comment)
- refactoring the way values get committed to ...Requests when the Start Ventilation button is pressed: #359 (comment)

**Comment by ethanjli** [comment]
Can you copy over the items which are split off from that comment into this issue, just to make clear what is the scope of this issue?
